
services:
  phasetwo-keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    command: start-dev --features organization --import-realm --spi-upload-scripts-enabled=true